# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Unit Tests

on:
  pull_request:
    branches:
    - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
    - name: Setup Node Environment
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Install Project Dependencies
      run: npm ci
    - name: Run Unit Tests
      run: npm run test
